### ISSUE TITLE
Branch for the future releases of DAB Specification

### ISSUE THREAD

**Issue by denisyuji** [device-automation-bus/dab-tools#9]
We are planning to update existing code with future releases of DAB Specification.
Would it be possible to create a new branch for the next release?

**Comment by denisyuji** [comment]
@amzn-stenlaan , can you help me by creating a 2.0 branch, so I can send a PR for the dab-rdk bridge? Thank you!

**Comment by amzn-stenlaan** [comment]
I've created the 2.0 branch for this: https://github.com/device-automation-bus/dab-tools/tree/2.0
